<x-app-layout>
<x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">Cadastrar médico</h2></x-slot>
<div class="py-12"><div class="max-w-3xl mx-auto sm:px-6 lg:px-8"><div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg"><form method="POST" action="{{ route('medicos.store') }}" class="p-6 space-y-6 text-gray-900 dark:text-gray-100">@csrf
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
<div><label class="block text-sm font-medium text-slate-700">Nome</label><input name="nome" value="{{ old('nome') }}" required class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">CRM</label><input name="crm" value="{{ old('crm') }}" required class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">E-mail</label><input type="email" name="email" value="{{ old('email') }}" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">Telefone</label><input name="telefone" value="{{ old('telefone') }}" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">Especialidade</label><select name="especialidade_id" required class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500">@foreach($especialidades as $e)<option value="{{ $e->id }}" @selected(old('especialidade_id')==$e->id)>{{ $e->nome }}</option>@endforeach</select></div>
<div><label class="block text-sm font-medium text-slate-700">Unidade/Consultório</label><select name="unidade_consultorio_id" required class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500">@foreach($unidadesConsultorios as $u)<option value="{{ $u->id }}" @selected(old('unidade_consultorio_id')==$u->id)>{{ $u->nome }}</option>@endforeach</select></div>
<div><label class="block text-sm font-medium text-slate-700">Usuário de acesso</label><select name="user_id" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500">@foreach($users as $u)<option value="{{ $u->id }}" @selected(old('user_id')==$u->id)>{{ $u->name }}</option>@endforeach</select></div>
<div><label class="block text-sm font-medium text-slate-700">Status</label><select name="ativo" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"><option value="1" @selected(old('ativo',1)==1)>Ativo</option><option value="0" @selected(old('ativo',1)==0)>Inativo</option></select></div>
</div><div class="flex gap-3"><x-primary-button>Salvar</x-primary-button><a href="{{ route('medicos.index') }}" class="inline-flex items-center px-4 py-2 bg-slate-100 border border-slate-300 rounded-md font-semibold text-xs text-slate-700 uppercase tracking-widest hover:bg-slate-200">Cancelar</a></div>
</form></div></div></div></x-app-layout>
