<x-app-layout>
<x-slot name="header"><h2 class="font-semibold text-xl text-slate-800">Editar médico</h2></x-slot>
<div class="py-8"><div class="max-w-4xl mx-auto sm:px-6 lg:px-8"><div class="bg-white shadow-sm rounded-xl border border-slate-200"><form method="POST" action="{{ route('medicos.update', $medico) }}" class="p-6 space-y-6">@csrf @method('PUT')
<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
<div><label class="block text-sm font-medium text-slate-700">Nome</label><input name="nome" value="{{ old('nome',$medico->nome) }}" required class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">CRM</label><input name="crm" value="{{ old('crm',$medico->crm) }}" required class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">E-mail</label><input type="email" name="email" value="{{ old('email',$medico->email) }}" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">Telefone</label><input name="telefone" value="{{ old('telefone',$medico->telefone) }}" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"></div>
<div><label class="block text-sm font-medium text-slate-700">Especialidade</label><select name="especialidade_id" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500">@foreach($especialidades as $e)<option value="{{ $e->id }}" @selected(old('especialidade_id',$medico->especialidade_id)==$e->id)>{{ $e->nome }}</option>@endforeach</select></div>
<div><label class="block text-sm font-medium text-slate-700">Usuário de acesso</label><select name="user_id" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500">@foreach($users as $u)<option value="{{ $u->id }}" @selected(old('user_id',$medico->user_id)==$u->id)>{{ $u->name }}</option>@endforeach</select></div>
<div><label class="block text-sm font-medium text-slate-700">Status</label><select name="ativo" class="mt-1 w-full rounded-lg border-slate-300 focus:border-teal-500 focus:ring-teal-500"><option value="1" @selected(old('ativo',$medico->ativo)==1)>Ativo</option><option value="0" @selected(old('ativo',1)==0)>Inativo</option></select></div>
</div><div class="flex gap-3"><button class="px-5 py-2.5 rounded-lg bg-teal-600 hover:bg-teal-700 text-white">Salvar</button><a href="{{ route('medicos.index') }}" class="px-5 py-2.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700">Cancelar</a></div>
</form></div></div></div></x-app-layout>
